[package]
name = "psx"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
logger = { path = "logger" }

bitfield = "0.19.0"
byteorder = "1.5.0"
ctrlc = "3.4.6"
gl = "0.14.0"
lazy_static = "1.4.0"
ringbuffer = "0.8.2"
rustyline = "9.0.0"
sdl3 = { git = "https://github.com/revmischa/sdl3-rs" } 

[profile.dev]
# Reduce 33.8Mhz from 22 seconds to 1.7 seconds even in dev mode
opt-level = 1

[target.'cfg(target_os = "macos")'.dependencies.sdl2]
features = ["bundled"]
version = "0.37.0"