[package]
name = "psx"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpu = { path = "cpu" }
logger = { path = "logger" }

bitfield = "0.13.2"
byteorder = "1.4.3"
ctrlc = "3.2.1"
gl = "0.14.0"
lazy_static = "1.4.0"
ringbuffer = "0.8.2"
rustyline = "9.0.0"
sdl2 = "0.37.0"

[profile.dev]
# Reduce 33.8Mhz from 22 seconds to 1.7 seconds even in dev mode
opt-level = 1

[target.'cfg(target_os = "macos")'.dependencies.sdl2]
features = ["bundled"]
version = "0.37.0"